//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.20 at 09:49:52 AM CET 
//


package org.oasis.ebxml.registry.bindings.lcm;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.oasis.ebxml.registry.bindings.lcm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RepositoryItemList_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0:ext", "RepositoryItemList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.oasis.ebxml.registry.bindings.lcm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UndeprecateObjectsRequest }
     * 
     */
    public UndeprecateObjectsRequest createUndeprecateObjectsRequest() {
        return new UndeprecateObjectsRequest();
    }

    /**
     * Create an instance of {@link AcceptObjectsRequest }
     * 
     */
    public AcceptObjectsRequest createAcceptObjectsRequest() {
        return new AcceptObjectsRequest();
    }

    /**
     * Create an instance of {@link RemoveObjectsRequest }
     * 
     */
    public RemoveObjectsRequest createRemoveObjectsRequest() {
        return new RemoveObjectsRequest();
    }

    /**
     * Create an instance of {@link SubmitObjectsRequest }
     * 
     */
    public SubmitObjectsRequest createSubmitObjectsRequest() {
        return new SubmitObjectsRequest();
    }

    /**
     * Create an instance of {@link DeprecateObjectsRequest }
     * 
     */
    public DeprecateObjectsRequest createDeprecateObjectsRequest() {
        return new DeprecateObjectsRequest();
    }

    /**
     * Create an instance of {@link RelocateObjectsRequest }
     * 
     */
    public RelocateObjectsRequest createRelocateObjectsRequest() {
        return new RelocateObjectsRequest();
    }

    /**
     * Create an instance of {@link UpdateObjectsRequest }
     * 
     */
    public UpdateObjectsRequest createUpdateObjectsRequest() {
        return new UpdateObjectsRequest();
    }

    /**
     * Create an instance of {@link ApproveObjectsRequest }
     * 
     */
    public ApproveObjectsRequest createApproveObjectsRequest() {
        return new ApproveObjectsRequest();
    }

    /**
     * Create an instance of {@link SetStatusOnObjectsRequest }
     * 
     */
    public SetStatusOnObjectsRequest createSetStatusOnObjectsRequest() {
        return new SetStatusOnObjectsRequest();
    }

    /**
     * Create an instance of {@link RepositoryItemListType }
     * 
     */
    public RepositoryItemListType createRepositoryItemListType() {
        return new RepositoryItemListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RepositoryItemListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0:ext", name = "RepositoryItemList")
    public JAXBElement<RepositoryItemListType> createRepositoryItemList(RepositoryItemListType value) {
        return new JAXBElement<RepositoryItemListType>(_RepositoryItemList_QNAME, RepositoryItemListType.class, null, value);
    }

}
