//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.20 at 09:49:52 AM CET 
//


package org.oasis.ebxml.registry.bindings.query;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseOptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseOptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="returnType" default="RegistryObject">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *             &lt;enumeration value="ObjectRef"/>
 *             &lt;enumeration value="RegistryObject"/>
 *             &lt;enumeration value="LeafClass"/>
 *             &lt;enumeration value="LeafClassWithRepositoryItem"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="returnComposedObjects" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseOptionType")
public class ResponseOptionType
    implements Serializable
{

    private final static long serialVersionUID = 30L;
    @XmlAttribute(name = "returnType")
    protected ResponseOptionType.ReturnType returnType;
    @XmlAttribute(name = "returnComposedObjects")
    protected Boolean returnComposedObjects;

    /**
     * Gets the value of the returnType property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseOptionType.ReturnType }
     *     
     */
    public ResponseOptionType.ReturnType getReturnType() {
        if (returnType == null) {
            return ResponseOptionType.ReturnType.REGISTRY_OBJECT;
        } else {
            return returnType;
        }
    }

    /**
     * Sets the value of the returnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseOptionType.ReturnType }
     *     
     */
    public void setReturnType(ResponseOptionType.ReturnType value) {
        this.returnType = value;
    }

    /**
     * Gets the value of the returnComposedObjects property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isReturnComposedObjects() {
        if (returnComposedObjects == null) {
            return false;
        } else {
            return returnComposedObjects;
        }
    }

    /**
     * Sets the value of the returnComposedObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnComposedObjects(Boolean value) {
        this.returnComposedObjects = value;
    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
     *     &lt;enumeration value="ObjectRef"/>
     *     &lt;enumeration value="RegistryObject"/>
     *     &lt;enumeration value="LeafClass"/>
     *     &lt;enumeration value="LeafClassWithRepositoryItem"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum ReturnType {

        @XmlEnumValue("ObjectRef")
        OBJECT_REF("ObjectRef"),
        @XmlEnumValue("RegistryObject")
        REGISTRY_OBJECT("RegistryObject"),
        @XmlEnumValue("LeafClass")
        LEAF_CLASS("LeafClass"),
        @XmlEnumValue("LeafClassWithRepositoryItem")
        LEAF_CLASS_WITH_REPOSITORY_ITEM("LeafClassWithRepositoryItem");
        private final String value;

        ReturnType(String v) {
            value = v;
        }

        public String value() {
            return value;
        }

        public static ResponseOptionType.ReturnType fromValue(String v) {
            for (ResponseOptionType.ReturnType c: ResponseOptionType.ReturnType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
            throw new IllegalArgumentException(v);
        }

    }

}
